#python 3.10.2 버전이라는 베이스 이미지를 사용해 새로운 이미지를 생성
FROM python:3.10.2
#작업 디렉토리를 /todolist_app으로 설정, 이 디렉토리는 이미지 내에서 모든 작업이 수행될 위치
WORKDIR /todolist_app
#현재 디렉토리의 모든 파일과 폴더가 이미지 내의 /todolist_app 디렉토리로 복사됨
COPY . .
#django를 이미지 내에서 실행시키기 위해 pip로 설치해야할 내용들을 설치하는 명령 실행
RUN pip install django
#컨테이너가 실행될 때 기본으로 실행할 명령 지정
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
#django 서버의 포트를 8000번으로 지정하였으므로 docker의 컨테이너 또한 8000 포트를 열어줌
EXPOSE 8000